---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: blat6
flagType: boolean
description: "this is a test to see if description will be saved to Unify"
labels:

availableValues:
  - "false"
  - "true"

isPermanent: false
